# Generated by Django 3.2.18 on 2025-03-07 22:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='food_items',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
